### PR TITLE
Spec, Conf label issue fixed

### LINKED ISSUE #3: Labels for Program Arguments "Specification" and "Configuration" should always be visible
The names of specifications and configurations are not always speaking,
so it would help usability if the labels "Specification" (or "Spec.") and "Configuration (or "Config.") were always visible next to or above the dropdown menus for the corresponding values.

### PR DESCRIPTION
**Pull request by lembergerth**
Fixes #3 .

@SupunArunoda  could you please take a look at the commit and make sure that it is what you intended?

### CODE REVIEW

**Comment by SupunArunoda** [comment]
Hi Thomas,
Yes of course. This is the code change I have done. I think we can merge now

**Comment by leostrakosch** [comment]
Hi Supun,

I had to do a merge for the cherry pick, so maybe I resolved the conflicts wrong. Are you certain it‘s correct.

**Comment by SupunArunoda** [comment]
Hi Thomas,
I didn't see this comment. I am sure this is the change I have done.

**Comment by lembergerth** [comment]
Alright, thanks! :)

**Pull request merged**
