### PR TITLE
Fixed #9

### LINKED ISSUE #9: CPACEP should be Operating-System agnostic
Currently, CPACEP only works in Linux/Unix(?) systems
because the file delimiter `/` is hard-coded
and it is assumed that the temporary directory is created in `/tmp/`.

This makes it unusable at least in Windows.

Instead, we should use `File.separator` as path delimiters
and remember the created temporary directory.

### PR DESCRIPTION
**Pull request by SupunArunoda**
Hi @leostrakosch ,
I think that we need the validation to getting current os name. I couldn't validate on windows machine. However I think this should be work. Could you please let me know whether this is working on windows?

Thanks

### CODE REVIEW

**Comment by SupunArunoda** [comment]
Hi Thomas,
Fixed the issue from second commit. Tested on Linux environment. Could you please test that on Windows environment?

**Comment by leostrakosch** [comment]
Hi Supun,

I think there is one last location using "/" (well, two lines):

https://github.com/SupunArunoda/CPACEP/blob/e6bef55baa6581f50f65a67a183dba790bbd9165/org.eclipse.cpacep.ui/src/org/eclipse/internal/cpacep/launcher/MainLaunchingTab.java#L246

**Comment by SupunArunoda** [comment]
Hi Thomas,
My bad. Forgot to add those files.

**Comment by leostrakosch** [comment]
Hi Supun, again, please don't do this.
I actually had a review pending.

**Comment by leostrakosch** [comment]
Btw: This merge re-introduced in commit e6bef55ba the erroneous `toLowerCase()` in the FileHandler. You should be careful when resolving merge conflicts.

**Pull request merged**
