### PR TITLE
Spec and Conf label changed with resolution

### PR DESCRIPTION
**Pull request by SupunArunoda**
Hi,
Setup the labels spec and conf labels. [Issue 3](https://github.com/SupunArunoda/CPACEP/issues/3)
screenshot from 2018-06-16 15-40-39

### CODE REVIEW

**Comment by leostrakosch** [comment]
If I understood the code correctly, you are having a 2-column grid with the Specification and Configuration
and some margin, and below that a 3-column grid with the "Program Specification" label and the two combo boxes.
So the lables and combo boxes are still not linked, but only below each other because of the correct spacing.
If I change something now, I still have to adjust the spacing every time.
How about creating a three-column grid that contains the "Program Specification" label in the first column, and label + combo box in the two other columns?
This way, they will always be below each other, becaues they are directly coupled.

**Comment by SupunArunoda** [comment]
Hi @leostrakosch ,
Did you review this pull request? I think the issue is fixed now.

**Comment by SupunArunoda** [comment]
Hi Thomas,
Updated the repository with code formatter.

**Comment by leostrakosch** [comment]
Oh ok, now everything is changed.
Can't you just run the code formatter on the changed lines of code? It works in the CPAchecker project, maybe look there for how to if it doesn't work yet.

**Comment by SupunArunoda** [comment]
Hi Thomas,
Changes are in MainLaunchingTab class. Should I reformat that class only then??

**Comment by leostrakosch** [comment]
No, you should only format the changed lines of code.

A quick look at the google java format project README referred me to this:

https://github.com/google/google-java-format/blob/master/scripts/google-java-format-diff.py

And in the CPAchecker project, it is used in an [ant task][1].

[1]: https://github.com/sosy-lab/cpachecker/blob/e5efbd2838eb77ee12e1a629b57aff01b5848516/build/build-format-source.xml#L38

**Comment by leostrakosch** [comment]
Hi @SupunArunoda ,
can you resolve this PR by tomorrow?

**Comment by SupunArunoda** [comment]
Hi Thomas,
This has resolved. It is still open because the code formatter problem.

**Comment by SupunArunoda** [comment]
Hi @leostrakosch 
This is fixed now.

**Comment by leostrakosch** [comment]
Replaced by new PR #41 without any code format.

**Pull request closed without merging**
